[project]
name = "jbnu-qwen3-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "qwen-agent[mcp]>=0.0.27",
    "streamlit>=1.46.1",
    "vllm>=0.9",
]
